Traceback (most recent call last):
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/aaron/miniforge3/envs/eeg/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# select data based on time window
df_stim = df[(df['time'] > stim_on_time) & (df['time'] <= stim_off_time)]

fig = plt.figure(figsize=[10,15])
subplot_counter = 1

for neuron in neuron_labels:
    neu_dat = df_stim[(df_stim['neuron'] == neuron)]

    ax = fig.add_subplot(num_neurons, 3, subplot_counter)

    for cond in cond_labels:
        
        tmp_dat = neu_dat[(neu_dat['condition'] == cond)] 

        spike_rate = np.zeros([num_contr, 2])

        for contr in enumerate(contr_labels):
            spike_count = tmp_dat[(tmp_dat['contrast'] == contr[1]) &
                                  (tmp_dat['spike'] == 1)
                                 ]['spike'].count()

            spike_rate[contr[0]][0] = contr[1]
            spike_rate[contr[0]][1] = spike_count / (stim_off_time - stim_on_time)
            
        ax.plot(spike_rate[:,0], spike_rate[:,1])
                
    plt.title(neuron )
    plt.xlabel('Contrast (%)')
    plt.ylabel('Spike Rate')
    subplot_counter += 1
    plt.tight_layout()

plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/var/folders/x0/pvpjfdzd39sc5rqvsk5lvv4m0000gn/T/ipykernel_6415/1909455439.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# select data based on time window[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0mdf_stim[0m [0;34m=[0m [0mdf[0m[0;34m[[0m[0;34m([0m[0mdf[0m[0;34m[[0m[0;34m'time'[0m[0;34m][0m [0;34m>[0m [0mstim_on_time[0m[0;34m)[0m [0;34m&[0m [0;34m([0m[0mdf[0m[0;34m[[0m[0;34m'time'[0m[0;34m][0m [0;34m<=[0m [0mstim_off_time[0m[0;34m)[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mfig[0m [0;34m=[0m [0mplt[0m[0;34m.[0m[0mfigure[0m[0;34m([0m[0mfigsize[0m[0;34m=[0m[0;34m[[0m[0;36m10[0m[0;34m,[0m[0;36m15[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0msubplot_counter[0m [0;34m=[0m [0;36m1[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'df' is not defined
NameError: name 'df' is not defined

